In [1]:
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

# This makes it so this notebook file can access python files in ../src/
# project_root = Path.cwd().parent
# sys.path.insert(0, str(project_root))

# And then we can import our functions
from src.config import load_yaml_config
from src.data import load_data

pd.set_option('display.max_columns', None)

In [2]:
# config = load_yaml_config(project_root / "config.yaml")
config = load_yaml_config("config.yaml")
df = load_data(config["data"]["csv_paths"]["train"])

In [7]:
display(df)

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,spend_next_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise
0,558.11,510.90,453.75,104.36,0.0,0.00,57.15,153.099911,4.0,1.0,1,359.04,79.0,126.0,2.0,858.30,429.150000,112.656252,349.49,508.81,47.000000,NaN,0.0,0.00,1.0,349.49,2.0,858.30,2.0,858.30,660784,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,10000000,-0.660448
1,978.80,830.02,795.77,183.03,0.0,0.00,34.25,472.943134,32.0,1.0,1,592.71,244.0,616.0,5.0,6722.83,1344.566000,1683.795178,84.38,4222.15,93.000000,117.657696,0.0,0.00,0.0,0.00,0.0,0.00,4.0,2500.68,189146,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,10000001,0.924510
2,10.33,12.00,8.40,1.93,0.0,0.00,3.60,6.097485,1.0,1.0,1,423.72,9.0,610.0,90.0,17590.08,195.445333,190.389932,4.54,1002.15,6.752809,6.384073,2.0,111.27,9.0,1928.55,28.0,5290.25,49.0,7899.80,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,10000002,-0.258730
3,856.83,696.61,696.61,160.22,0.0,0.00,0.00,408.167275,9.0,1.0,0,NaN,97.0,97.0,1.0,270.33,270.330000,NaN,270.33,270.33,NaN,NaN,0.0,0.00,0.0,0.00,1.0,270.33,1.0,270.33,512927,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,10000003,1.448402
4,1616.10,1488.85,1313.90,302.20,0.0,0.00,174.95,485.401864,33.0,1.0,1,455.73,85.0,1575.0,25.0,12803.02,512.120800,406.696963,22.58,1736.74,62.083333,66.246520,0.0,0.00,2.0,184.13,4.0,2062.50,4.0,2062.50,122356,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,10000004,-1.058890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6529,3023.34,3761.38,2458.00,565.34,0.0,0.00,1303.38,1099.190000,49.0,1.0,1,1467.29,16.0,196.0,5.0,5548.20,1109.640000,1213.808411,254.47,3041.05,45.000000,22.700954,2.0,562.31,3.0,3603.36,4.0,3962.95,5.0,5548.20,151492,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 3,2016-01-24,10007670,-1.579719
6530,1362.26,1723.10,1107.53,254.73,0.0,34.25,581.32,197.514000,16.0,1.0,0,NaN,367.0,367.0,1.0,625.91,625.910000,NaN,625.91,625.91,NaN,NaN,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,975873,Maybe Tomorrow Payment 12,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 1,2021-04-13,10007671,-0.576883
6531,4396.55,3574.43,3574.43,822.12,0.0,0.00,0.00,2075.838024,78.0,1.0,1,2696.35,77.0,2331.0,78.0,102675.07,1316.347051,1295.241815,3.20,6144.21,29.272727,29.017525,0.0,0.00,2.0,2214.29,7.0,14817.28,13.0,27824.52,755628,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 2,2022-03-19,10007672,0.528377
6532,452.07,483.60,367.54,84.53,0.0,0.00,116.06,265.159468,7.0,1.0,1,7051.17,14.0,874.0,34.0,35318.25,1038.772059,1256.647055,3.35,5019.81,26.060606,25.290734,1.0,1241.86,5.0,1855.15,9.0,4922.16,14.0,12484.20,703834,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 40,Final Excel Warehouse 1,Ctrl Z Series 1,2019-03-23,10007673,1.012809
6533,951.71,982.00,773.75,177.96,0.0,0.00,208.25,224.543079,30.0,1.0,0,NaN,NaN,900.0,18.0,8178.65,454.369444,426.275692,94.61,1550.57,48.117647,49.176827,0.0,0.00,1.0,94.61,4.0,2159.31,5.0,2256.28,438652,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 73,Final Excel Warehouse 1,Ctrl Z Series 3,2019-11-23,10007674,-0.041337

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6534 entries, 0 to 6533
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Total a Pagar                   6469 non-null   float64
 1   Total Bruto                     6469 non-null   float64
 2   Total Liquido                   6469 non-null   float64
 3   Total Imp_                      6469 non-null   float64
 4   Total Portes                    6469 non-null   float64
 5   Total Desc_ Global              6469 non-null   float64
 6   Total Desc_ Linha               6469 non-null   float64
 7   Custo                           6469 non-null   float64
 8   N_ Detalhes                     6469 non-null   float64
 9   invoice_count_current_purchase  6469 non-null   float64
 10  repeat_purchase_90d             6534 non-null   int64
 11  spend_next_90d                  3425 non-null   float64
 12  days_since_previous_purchase    5673 non-null   float64
 13  customer_tenure_days            6469 non-null   float64
 14  prior_purchase_count            6469 non-null   float64
 15  prior_total_spend               6469 non-null   float64
 16  prior_mean_purchase_value       5672 non-null   float64
 17  prior_std_purchase_value        5421 non-null   float64
 18  prior_min_purchase_value        5866 non-null   float64
 19  prior_max_purchase_value        5866 non-null   float64
 20  prior_mean_gap_days             5226 non-null   float64
 21  prior_std_gap_days              5056 non-null   float64
 22  purchase_count_30d              6469 non-null   float64
 23  spend_30d                       6469 non-null   float64
 24  purchase_count_90d              6469 non-null   float64
 25  spend_90d                       6469 non-null   float64
 26  purchase_count_180d             6469 non-null   float64
 27  spend_180d                      6469 non-null   float64
 28  purchase_count_365d             6469 non-null   float64
 29  spend_365d                      6274 non-null   float64
 30  customer_id                     6534 non-null   int64
 31  payment_type                    6274 non-null   str
 32  salesperson                     6275 non-null   str
 33  commercial_zone                 6469 non-null   str
 34  transport_method                6273 non-null   str
 35  warehouse                       6274 non-null   str
 36  document_series                 6469 non-null   str
 37  purchase_date                   6469 non-null   str
 38  ID                              6534 non-null   int64
 39  random_noise                    6469 non-null   float64
dtypes: float64(30), int64(3), str(7)
memory usage: 2.0 MB

In [10]:
# Check the percentage of missing values for each column:
round(df.isna().sum() / len(df) * 100, 2)

Total a Pagar                      0.99
Total Bruto                        0.99
Total Liquido                      0.99
Total Imp_                         0.99
Total Portes                       0.99
Total Desc_ Global                 0.99
Total Desc_ Linha                  0.99
Custo                              0.99
N_ Detalhes                        0.99
invoice_count_current_purchase     0.99
repeat_purchase_90d                0.00
spend_next_90d                    47.58
days_since_previous_purchase      13.18
customer_tenure_days               0.99
prior_purchase_count               0.99
prior_total_spend                  0.99
prior_mean_purchase_value         13.19
prior_std_purchase_value          17.03
prior_min_purchase_value          10.22
prior_max_purchase_value          10.22
prior_mean_gap_days               20.02
prior_std_gap_days                22.62
purchase_count_30d                 0.99
spend_30d                          0.99
purchase_count_90d                 0.99
spend_90d                          0.99
purchase_count_180d                0.99
spend_180d                         0.99
purchase_count_365d                0.99
spend_365d                         3.98
customer_id                        0.00
payment_type                       3.98
salesperson                        3.96
commercial_zone                    0.99
transport_method                   3.99
warehouse                          3.98
document_series                    0.99
purchase_date                      0.99
ID                                 0.00
random_noise                       0.99
dtype: float64

In [11]:
df.describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,spend_next_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,ID,random_noise
count,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6534.000000,3425.000000,5673.000000,6469.000000,6469.000000,6469.000000,5.672000e+03,5421.000000,5866.000000,5866.000000,5226.000000,5056.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6469.000000,6.274000e+03,6534.000000,6.534000e+03,6469.000000
mean,925.556262,886.152705,773.336384,152.219878,1.151427,0.349907,112.466414,328.165040,21.524501,1.066007,0.559229,1921.531650,101.530231,1111.383676,23.457876,18908.348876,2.821825e+06,737.469683,185.462003,2946.378367,95.876660,74.135443,0.600557,457.141009,1.631937,1253.527977,3.374556,2650.599796,6.561601,2.396535e+06,506471.910621,1.000383e+07,-0.022140
std,1334.997733,1327.641086,1136.355723,225.262375,5.844091,5.116564,289.986307,519.507218,27.713419,0.310807,0.496518,2571.052046,165.704875,923.190795,38.344845,31130.865216,5.304157e+07,666.261939,408.398582,5901.547558,122.589306,101.819540,1.214975,1191.231401,2.977981,2347.842270,5.460510,4020.267397,10.325535,4.884113e+07,266556.041526,2.218817e+03,1.001054
min,0.930000,0.830000,0.760000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.270000,-4.000000,0.000000,0.000000,0.000000,-2.478658e+03,0.000000,0.930000,3.310000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.591152e+05,103940.000000,1.000000e+07,-3.529210
25%,188.920000,175.740000,154.380000,29.930000,0.000000,0.000000,0.000000,49.050000,4.000000,1.000000,0.000000,318.480000,17.000000,308.000000,3.000000,1505.550000,3.595581e+02,258.560327,15.450000,834.530000,42.596591,32.736068,0.000000,0.000000,0.000000,0.000000,1.000000,149.160000,1.000000,6.377825e+02,258332.000000,1.000191e+07,-0.677770
50%,476.740000,445.740000,389.910000,79.740000,0.000000,0.000000,13.130000,152.540000,11.000000,1.000000,1.000000,985.740000,57.000000,918.000000,11.000000,6754.310000,7.248970e+02,569.077581,64.340000,1783.240000,68.444444,50.635354,0.000000,0.000000,1.000000,198.500000,2.000000,1117.680000,3.000000,2.426605e+03,489625.000000,1.000382e+07,-0.045714
75%,1087.670000,1036.700000,903.370000,184.840000,0.000000,0.000000,92.280000,396.061499,29.000000,1.000000,1.000000,2464.560000,119.000000,1759.000000,27.000000,21642.320000,1.095887e+03,981.093653,162.610000,3504.420000,113.831579,78.626119,1.000000,338.240000,2.000000,1514.560000,3.000000,3404.440000,7.000000,7.045423e+03,755628.000000,1.000576e+07,0.641711
90%,2301.730000,2179.218000,1913.754000,372.432000,4.426000,0.000000,297.286000,812.524091,56.000000,1.000000,1.000000,5092.358000,231.000000,2484.000000,54.000000,51442.608000,1.775508e+03,1539.254083,433.090000,5737.910000,174.408333,138.019536,2.000000,1463.348000,4.000000,3872.704000,7.000000,7252.382000,13.000000,1.363526e+04,901016.000000,1.000690e+07,1.276995
95%,3398.774000,3251.836000,2838.592000,549.120000,5.750000,0.000000,540.394000,1227.526013,75.000000,2.000000,1.000000,6800.260000,337.000000,2904.000000,88.000000,83478.586000,2.564820e+03,1979.621578,820.700000,8050.330000,263.250000,220.574944,3.000000,2528.624000,8.000000,5828.656000,16.000000,10479.206000,31.000000,2.222760e+04,942170.000000,1.000729e+07,1.643549
99%,6543.971200,6717.615200,5675.703200,1026.788800,11.800000,7.846400,1369.040000,2382.102043,128.000000,2.000000,1.000000,12115.807600,787.120000,3318.000000,211.320000,158299.744400,5.230092e+03,3163.449043,1905.350000,14433.410000,514.100000,486.335676,6.000000,5396.487200,16.000000,10875.438800,28.000000,19209.804400,53.000000,4.087680e+04,984211.670000,1.000760e+07,2.326001
max,22297.210000,21578.280000,18127.810000,4169.400000,181.060000,218.490000,4103.440000,7427.400583,423.000000,5.000000,1.000000,25654.330000,3199.000000,3506.000000,276.000000,247865.100000,1.000000e+09,6770.221342,6298.980000,267526.189924,3199.000000,2212.537118,11.000000,22297.210000,22.000000,30234.880000,37.000000,49746.970000,60.000000,1.000000e+09,998870.000000,1.000767e+07,4.151241

In [20]:
display(df['payment_type'].value_counts(dropna=False))

payment_type
Maybe Tomorrow Payment 7     4565
Maybe Tomorrow Payment 12     991
Maybe Tomorrow Payment 9      502
NaN                           260
Maybe Tomorrow Payment 10     134
Maybe Tomorrow Payment 8       40
Maybe Tomorrow Payment 2       21
Maybe Tomorrow Payment 4        9
Maybe Tomorrow Payment 11       8
Maybe Tomorrow Payment 3        4
Name: count, dtype: int64

In [21]:
display(df['salesperson'].value_counts(dropna=False))

salesperson
VLOOKUP Master 1    4054
VLOOKUP Master 4    1461
VLOOKUP Master 9     384
NaN                  259
VLOOKUP Master 7     201
VLOOKUP Master 2     123
VLOOKUP Master 3      30
VLOOKUP Master 6      12
VLOOKUP Master 5       7
VLOOKUP Master 8       3
Name: count, dtype: int64

In [22]:
display(df['commercial_zone'].value_counts(dropna=False))

commercial_zone
Decorative Dashboard Zone 4    6260
Decorative Dashboard Zone 2     151
NaN                              65
Decorative Dashboard Zone 3      56
Decorative Dashboard Zone 6       1
Decorative Dashboard Zone 7       1
Name: count, dtype: int64

In [23]:
display(df['transport_method'].value_counts(dropna=False))

transport_method
Maybe Tomorrow Delivery 72    1119
Maybe Tomorrow Delivery 61     627
Maybe Tomorrow Delivery 73     445
Maybe Tomorrow Delivery 59     373
Maybe Tomorrow Delivery 80     319
                              ...
Maybe Tomorrow Delivery 55       1
Maybe Tomorrow Delivery 58       1
Maybe Tomorrow Delivery 28       1
Maybe Tomorrow Delivery 21       1
Maybe Tomorrow Delivery 23       1
Name: count, Length: 81, dtype: int64

In [24]:
display(df['warehouse'].value_counts(dropna=False))

warehouse
Final Excel Warehouse 1    6253
NaN                         260
Final Excel Warehouse 3      21
Name: count, dtype: int64

In [25]:
display(df['document_series'].value_counts(dropna=False))

document_series
Ctrl Z Series 2    2738
Ctrl Z Series 3    1903
Ctrl Z Series 1    1828
NaN                  65
Name: count, dtype: int64

In [42]:
df[df['prior_mean_purchase_value'] > 550000]

,Total a Pagar,Total Bruto,Total Liquido,Total Imp_,Total Portes,Total Desc_ Global,Total Desc_ Linha,Custo,N_ Detalhes,invoice_count_current_purchase,repeat_purchase_90d,spend_next_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise
196,142.99,116.25,116.25,26.74,0.0,0.0,0.00,29.750000,5.0,1.0,0,NaN,6.0,644.0,9.0,12364.88,1.000000e+09,1106.518954,50.63,3568.98,79.750000,63.744468,1.0,1988.15,1.0,1988.15,3.0,4497.87,4.0,NaN,112532,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 53,Final Excel Warehouse 1,Ctrl Z Series 1,2017-08-04,10000226,-0.493338
267,814.53,899.07,662.22,152.31,0.0,0.0,236.85,482.155516,24.0,1.0,1,94.02,NaN,1065.0,16.0,8663.31,1.000000e+09,342.270420,35.61,1130.41,63.933333,36.322891,0.0,0.00,0.0,0.00,2.0,1816.90,5.0,3094.49,175924,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 2,2021-10-17,10000304,-0.652678
1618,1200.58,1041.12,976.08,224.50,0.0,0.0,65.04,652.395497,57.0,1.0,1,672.06,21.0,483.0,9.0,10323.88,1.000000e+09,812.402520,176.53,2264.21,57.750000,26.315395,1.0,1013.80,1.0,1013.80,3.0,4986.92,6.0,6293.69,856505,Maybe Tomorrow Payment 7,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 46,Final Excel Warehouse 1,Ctrl Z Series 3,2016-11-06,10001890,-0.209193
2386,3312.75,3035.12,2693.29,619.46,0.0,0.0,341.83,1196.797840,35.0,1.0,1,1305.65,63.0,267.0,8.0,5074.04,1.000000e+09,363.070167,182.56,1260.04,29.142857,16.293440,0.0,0.00,1.0,374.49,4.0,2437.50,8.0,5074.04,218902,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 2,2024-06-15,10002792,-0.852592
2448,232.24,292.45,188.81,43.43,4.5,0.0,103.64,78.525348,45.0,2.0,1,5164.20,10.0,1253.0,112.0,102493.92,1.000000e+09,854.729506,6.73,5475.14,11.198198,10.471450,3.0,883.98,7.0,3340.30,19.0,19610.78,34.0,35148.19,258332,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2022-04-29,10002865,0.791131
2643,1483.44,1211.12,1206.05,277.39,0.0,0.0,5.07,703.567106,68.0,1.0,0,NaN,699.0,827.0,4.0,1943.24,1.000000e+09,500.165820,144.53,1226.80,42.666667,60.451082,0.0,0.00,0.0,0.00,0.0,0.00,0.0,NaN,529840,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 59,Final Excel Warehouse 1,Ctrl Z Series 3,2019-10-26,10003106,2.036018
3164,18.45,15.00,15.00,3.45,0.0,0.0,0.00,0.000000,1.0,1.0,1,119.05,5.0,2335.0,39.0,5104.07,1.000000e+09,147.186175,9.59,834.53,61.315789,89.309091,2.0,235.55,2.0,235.55,4.0,294.87,4.0,294.87,180223,NaN,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 80,Final Excel Warehouse 1,Ctrl Z Series 2,2024-11-02,10003702,0.172496
3511,83.64,68.00,68.00,15.64,0.0,0.0,0.00,0.000000,2.0,1.0,0,NaN,27.0,27.0,1.0,390.01,1.000000e+09,NaN,390.01,390.01,NaN,NaN,1.0,390.01,1.0,390.01,1.0,390.01,1.0,390.01,136125,Maybe Tomorrow Payment 7,VLOOKUP Master 2,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 78,Final Excel Warehouse 1,Ctrl Z Series 3,2015-11-10,10004113,-0.698644
4735,1405.85,1280.61,1142.97,262.88,0.0,0.0,137.64,360.714666,44.0,1.0,1,NaN,189.0,839.0,11.0,6417.54,1.000000e+09,358.271111,85.28,1237.31,NaN,37.520365,0.0,0.00,0.0,0.00,0.0,0.00,3.0,1227.90,871356,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 59,Final Excel Warehouse 1,Ctrl Z Series 3,2017-10-28,10005563,-0.420258
5104,261.38,212.50,212.50,48.88,0.0,0.0,0.00,144.500000,3.0,1.0,0,NaN,32.0,151.0,2.0,521.57,1.000000e+09,175.935238,136.38,385.19,119.000000,NaN,0.0,0.00,1.0,385.19,2.0,521.57,2.0,521.57,111068,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 73,Final Excel Warehouse 1,Ctrl Z Series 2,2023-11-08,10006001,-0.053032
5142,11.02,9.75,9.75,1.27,0.0,0.0,0.00,6.375000,2.0,1.0,1,6790.17,1.0,918.0,16.0,31315.65,1.000000e+09,1394.504997,13.65,3542.55,61.133333,42.763246,1.0,3254.40,3.0,9325.89,4.0,9443.67,7.0,14999.97,547119,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 1,2018-05-05,10006049,-0.279928
5321,836.40,688.09,680.00,156.40,0.0,0.0,8.09,347.679331,4.0,1.0,1,1145.75,21.0,1617.0,39.0,39244.97,1.000000e+09,1650.570886,6.62,9323.40,42.000000,44.613051,1.0,684.88,2.0,1961.46,3.0,2738.55,6.0,5149.58,540086,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 3,2019-12-28,10006258,-0.410050
5679,442.09,359.42,359.42,82.67,0.0,0.0,0.00,200.696500,13.0,1.0,0,NaN,133.0,2568.0,35.0,30681.60,1.000000e+09,650.638791,45.46,2264.21,71.617647,54.743487,0.0,0.00,0.0,0.00,1.0,1727.82,2.0,2055.63,856505,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 46,Final Excel Warehouse 1,Ctrl Z Series 2,2022-07-23,10006668,-1.278410
6100,324.71,410.54,263.99,60.72,0.0,0.0,146.55,141.717231,12.0,1.0,1,2349.73,5.0,1538.0,220.0,47033.52,1.000000e+09,264.124281,4.54,2306.25,NaN,7.795553,7.0,1328.23,16.0,3286.89,25.0,4685.19,58.0,11598.14,103940,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 11,Final Excel Warehouse 1,Ctrl Z Series 2,2021-10-02,10007157,-0.323661
6133,669.53,592.50,592.50,77.03,0.0,0.0,0.00,232.500000,2.0,1.0,1,802.30,14.0,881.0,11.0,8391.76,1.000000e+09,252.396988,322.05,1167.55,86.700000,48.300104,1.0,880.54,1.0,880.54,3.0,2717.62,5.0,4415.90,427118,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 40,Final Excel Warehouse 1,Ctrl Z Series 1,2018-03-30,10007199,-1.363997
6362,1268.75,1031.50,1031.50,237.25,0.0,0.0,0.00,642.538770,9.0,1.0,0,NaN,28.0,3192.0,26.0,31014.16,1.000000e+09,1406.661623,91.94,4742.71,126.560000,85.781739,1.0,3789.80,1.0,3789.80,2.0,7851.67,5.0,15504.49,449027,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 2,2024-07-27,10007471,-1.685372

# Testing /src Code

In [3]:
from src.preprocessing import clean_dataset

In [4]:
cleaned = clean_dataset(df, config["cleaning"]["train"])

In [5]:
cleaned

,total_amount_payable,gross_total,net_total,total_tax,total_shipping,total_global_discount,total_line_item_discount,cost,details_count,invoice_count_current_purchase,repeat_purchase_90d,spend_next_90d,days_since_previous_purchase,customer_tenure_days,prior_purchase_count,prior_total_spend,prior_mean_purchase_value,prior_std_purchase_value,prior_min_purchase_value,prior_max_purchase_value,prior_mean_gap_days,prior_std_gap_days,purchase_count_30d,spend_30d,purchase_count_90d,spend_90d,purchase_count_180d,spend_180d,purchase_count_365d,spend_365d,customer_id,payment_type,salesperson,commercial_zone,transport_method,warehouse,document_series,purchase_date,ID,random_noise
0,558.11,510.90,453.75,104.36,0.0,0.00,57.15,153.099911,4,1,1,359.04,79,126,2,858.30,429.150000,112.656252,349.49,508.81,47.000000,NaN,0,0.00,1,349.49,2,858.30,2,858.30,660784.0,Maybe Tomorrow Payment 10,VLOOKUP Master 9,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2024-10-29,10000000,-0.660448
1,978.80,830.02,795.77,183.03,0.0,0.00,34.25,472.943134,32,1,1,592.71,244,616,5,6722.83,1344.566000,1683.795178,84.38,4222.15,93.000000,117.657696,0,0.00,0,0.00,0,0.00,4,2500.68,189146.0,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 36,Final Excel Warehouse 1,Ctrl Z Series 1,2017-07-08,10000001,0.924510
2,10.33,12.00,8.40,1.93,0.0,0.00,3.60,6.097485,1,1,1,423.72,9,610,90,17590.08,195.445333,190.389932,4.54,1002.15,6.752809,6.384073,2,111.27,9,1928.55,28,5290.25,49,7899.80,103940.0,Maybe Tomorrow Payment 9,VLOOKUP Master 1,Decorative Dashboard Zone 4,NaN,Final Excel Warehouse 1,Ctrl Z Series 3,2019-03-19,10000002,-0.258730
3,856.83,696.61,696.61,160.22,0.0,0.00,0.00,408.167275,9,1,0,NaN,97,97,1,270.33,270.330000,NaN,270.33,270.33,NaN,NaN,0,0.00,0,0.00,1,270.33,1,270.33,512927.0,Maybe Tomorrow Payment 7,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 71,Final Excel Warehouse 1,Ctrl Z Series 3,2018-11-10,10000003,1.448402
4,1616.10,1488.85,1313.90,302.20,0.0,0.00,174.95,485.401864,33,1,1,455.73,85,1575,25,12803.02,512.120800,406.696963,22.58,1736.74,62.083333,66.246520,0,0.00,2,184.13,4,2062.50,4,2062.50,122356.0,Maybe Tomorrow Payment 12,NaN,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 2,2021-11-30,10000004,-1.058890
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6529,3023.34,3761.38,2458.00,565.34,0.0,0.00,1303.38,1099.190000,49,1,1,1467.29,16,196,5,5548.20,1109.640000,1213.808411,254.47,3041.05,45.000000,22.700954,2,562.31,3,3603.36,4,3962.95,5,5548.20,151492.0,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 3,2016-01-24,10007670,-1.579719
6530,1362.26,1723.10,1107.53,254.73,0.0,34.25,581.32,197.514000,16,1,0,NaN,367,367,1,625.91,625.910000,NaN,625.91,625.91,NaN,NaN,0,0.00,0,0.00,0,0.00,0,0.00,975873.0,Maybe Tomorrow Payment 12,VLOOKUP Master 4,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 61,Final Excel Warehouse 1,Ctrl Z Series 1,2021-04-13,10007671,-0.576883
6531,4396.55,3574.43,3574.43,822.12,0.0,0.00,0.00,2075.838024,78,1,1,2696.35,77,2331,78,102675.07,1316.347051,1295.241815,3.20,6144.21,29.272727,29.017525,0,0.00,2,2214.29,7,14817.28,13,27824.52,755628.0,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 72,Final Excel Warehouse 1,Ctrl Z Series 2,2022-03-19,10007672,0.528377
6532,452.07,483.60,367.54,84.53,0.0,0.00,116.06,265.159468,7,1,1,7051.17,14,874,34,35318.25,1038.772059,1256.647055,3.35,5019.81,26.060606,25.290734,1,1241.86,5,1855.15,9,4922.16,14,12484.20,703834.0,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 40,Final Excel Warehouse 1,Ctrl Z Series 1,2019-03-23,10007673,1.012809
6533,951.71,982.00,773.75,177.96,0.0,0.00,208.25,224.543079,30,1,0,NaN,<NA>,900,18,8178.65,454.369444,426.275692,94.61,1550.57,48.117647,49.176827,0,0.00,1,94.61,4,2159.31,5,2256.28,438652.0,Maybe Tomorrow Payment 7,VLOOKUP Master 1,Decorative Dashboard Zone 4,Maybe Tomorrow Delivery 73,Final Excel Warehouse 1,Ctrl Z Series 3,2019-11-23,10007674,-0.041337

In [6]:
cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 6534 entries, 0 to 6533
Data columns (total 40 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   total_amount_payable            6469 non-null   float64
 1   gross_total                     6469 non-null   float64
 2   net_total                       6469 non-null   float64
 3   total_tax                       6469 non-null   float64
 4   total_shipping                  6469 non-null   float64
 5   total_global_discount           6469 non-null   float64
 6   total_line_item_discount        6469 non-null   float64
 7   cost                            6469 non-null   float64
 8   details_count                   6469 non-null   Int64
 9   invoice_count_current_purchase  6469 non-null   Int64
 10  repeat_purchase_90d             6534 non-null   Int64
 11  spend_next_90d                  3425 non-null   float64
 12  days_since_previous_purchase    5657 non-null   Int64
 13  customer_tenure_days            6469 non-null   Int64
 14  prior_purchase_count            6469 non-null   Int64
 15  prior_total_spend               6469 non-null   float64
 16  prior_mean_purchase_value       5656 non-null   float64
 17  prior_std_purchase_value        5421 non-null   float64
 18  prior_min_purchase_value        5866 non-null   float64
 19  prior_max_purchase_value        5866 non-null   float64
 20  prior_mean_gap_days             5210 non-null   float64
 21  prior_std_gap_days              5056 non-null   float64
 22  purchase_count_30d              6469 non-null   Int64
 23  spend_30d                       6469 non-null   float64
 24  purchase_count_90d              6469 non-null   Int64
 25  spend_90d                       6469 non-null   float64
 26  purchase_count_180d             6469 non-null   Int64
 27  spend_180d                      6469 non-null   float64
 28  purchase_count_365d             6469 non-null   Int64
 29  spend_365d                      6259 non-null   float64
 30  customer_id                     6534 non-null   float64
 31  payment_type                    6274 non-null   str
 32  salesperson                     6275 non-null   str
 33  commercial_zone                 6469 non-null   str
 34  transport_method                6273 non-null   str
 35  warehouse                       6274 non-null   str
 36  document_series                 6469 non-null   str
 37  purchase_date                   6469 non-null   datetime64[us]
 38  ID                              6534 non-null   Int64
 39  random_noise                    6469 non-null   float64
dtypes: Int64(11), datetime64[us](1), float64(22), str(6)
memory usage: 2.1 MB